name: Deploy Vite App on GitHb Pages

on:
  push:
    branches: ["SupDeCuisine"]
    
jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: NODE_ENV=development npm install